apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart
  namespace: shopping
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ekart
  template:
    metadata:
      labels:
        app: ekart
    spec:
      containers:
      - name: spring-boot-container
        image: praveen431ece/spring-boot:tagversion
        ports:
        - containerPort: 8070
---
apiVersion: v1
kind: Service
metadata:
  name: ekart-service
  namespace: shopping
spec:
  type: LoadBalancer
  selector:
    app: ekart
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8070
